name: Build Game

on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]
    
permissions:
  contents: read
  
jobs:
    build:
      
      runs-on: ubuntu-latest
      
      steps:
      - uses: actions/cache@v2
        with:
          path: /github/workspace/Library
          key: Library-CookingYnah-StandaloneWindows64
          restore-keys: |
            Library-CookingYnah-
            Library-
      - name: Checkout
        uses: actions/checkout@v3
      - name: Windows Build
        uses: game-ci/unity-builder@v2.2.0
        env:
            UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
            UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
            UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          buildName: Cooking Ynah
      - name: Upload artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
            path: build/
            name: Windows Build
