// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;

namespace CsBindgen
{
    internal static unsafe partial class TwitchRustRaw
    {
        const string __DllName = "libtwitch-irc";

        [DllImport(__DllName, EntryPoint = "init_runtime", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* init_runtime();

        [DllImport(__DllName, EntryPoint = "free_handle", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void free_handle(void* handle);

        [DllImport(__DllName, EntryPoint = "join_channel", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void join_channel(void* ctx, byte* s_ptr, int s_len);


    }



}
    